### ISSUE TITLE
Release library to artifactory

### ISSUE THREAD

**Issue by diegoagd10** [NovaMage/SValidator#1]
I was wondering why an awesome library like this is not in maven yet.

**Comment by NovaMage** [comment]
I was trying to refine it and document it to a point were I found it worthwhile to put it there.  But I think that time has come!  I'm just putting in the finishing touches of the documentation.  Thanks for the props! :D

**Comment by NovaMage** [comment]
As you can see [here](https://search.maven.org/#artifactdetails%7Ccom.github.novamage%7Csvalidator_2.12%7C0.9.2%7Cjar), SValidator is now available on Maven! :D 

I will close this issue now :3
